# Generated by Django 3.0.6 on 2020-06-01 08:45

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPonentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('apellido', models.CharField(max_length=32)),
                ('institucion', models.TextField()),
                ('bio_corto', models.TextField()),
                ('linkedin', models.TextField(null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('exp_personales_bool', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilSolicitante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('apellido', models.CharField(max_length=32)),
                ('institucion', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='TiposTopicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='TopicosSolicitados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TiposTopicos')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.PerfilSolicitante')),
            ],
        ),
        migrations.CreateModel(
            name='TopicosOfrecidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=256, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TiposTopicos')),
            ],
        ),
    ]
