# Generated by Django 3.0.6 on 2020-06-01 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicosofrecidos',
            name='ponente',
            field=models.ForeignKey(default='A definir', on_delete=django.db.models.deletion.DO_NOTHING, to='app.PerfilPonentes'),
        ),
    ]
